function _ssh_agent_start --description "Start a new ssh agent"
    # We use the -c flag to generate csh-style output of the form:
    # setenv SSH_AUTH_SOCK ...
    # This output is then converted to fish-style output.
    set -l ssh_output (ssh-agent -c)
    set -l filtered_output
    for line in $ssh_output
        if string match --quiet --regex '^echo' -- $line
            continue
        end
        set -l transformed (string replace 'setenv' 'set -gx' -- $line)
        set transformed (string replace --regex ';(\s*)$' '' -- $transformed)
        set --append filtered_output $transformed
    end

    echo "# Generated by fish-ssh-agent" >"$SSH_ENV"
    printf "%s\n" (string join \n $filtered_output) >>"$SSH_ENV"
    chmod 600 "$SSH_ENV"
    source "$SSH_ENV"
end
